services:
  - type: web
    name: horizon-ai-podcast-generator
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: FIRECRAWL_API_KEY
        sync: false
      - key: MAX_UPLOAD_FILE_SIZE
        value: 20
      - key: NEXT_PUBLIC_MAX_UPLOAD_FILE_SIZE
        value: 20
